export interface Product {
  id: string;
  name: string;
  vendor: string;
  vendorVerified: boolean;
  category: string;
  categorySlug: string;
  image: string;
  imageAlt: string;
  price: number;
  originalPrice: number;
  discountPct: number;
  unit: string;
  stock: number;
  stockStatus: 'in_stock' | 'low_stock' | 'out_of_stock';
  rating: number;
  reviewCount: number;
  description: string;
  tags: string[];
  minOrder: number;
}

export const mockProducts: Product[] = [
{
  id: 'prod-001',
  name: 'DAP Fertilizer (Diammonium Phosphate)',
  vendor: 'Kisan Agro Supplies',
  vendorVerified: true,
  category: 'Fertilizers',
  categorySlug: 'fertilizers',
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1c6527fd8-1773210925312.png",
  imageAlt: 'White granular DAP fertilizer in an open bag on a wooden surface',
  price: 1350,
  originalPrice: 1600,
  discountPct: 16,
  unit: 'per 50kg bag',
  stock: 240,
  stockStatus: 'in_stock',
  rating: 4.7,
  reviewCount: 312,
  description: 'High-quality DAP fertilizer for paddy, wheat, and vegetable crops. 18-46-0 NPK ratio.',
  tags: ['paddy', 'wheat', 'rabi'],
  minOrder: 1
},
{
  id: 'prod-002',
  name: 'Hybrid Tomato Seeds — Arka Rakshak',
  vendor: 'Green Fields Seeds',
  vendorVerified: true,
  category: 'Seeds',
  categorySlug: 'seeds',
  image: "https://images.unsplash.com/photo-1694529674608-4702f575f9cb",
  imageAlt: 'Small red tomato seeds spread on a white tray with a seed packet nearby',
  price: 480,
  originalPrice: 550,
  discountPct: 13,
  unit: 'per 10g packet',
  stock: 85,
  stockStatus: 'in_stock',
  rating: 4.5,
  reviewCount: 197,
  description: 'Disease-resistant hybrid tomato variety. High yield, suitable for kharif and rabi seasons.',
  tags: ['tomato', 'hybrid', 'kharif'],
  minOrder: 2
},
{
  id: 'prod-003',
  name: 'Imidacloprid 17.8% SL Insecticide',
  vendor: 'BharatAgri Chem',
  vendorVerified: true,
  category: 'Pesticides',
  categorySlug: 'pesticides',
  image: "https://images.unsplash.com/photo-1644101211459-7f9be46fad04",
  imageAlt: 'Yellow pesticide spray bottle on a green agricultural field background',
  price: 340,
  originalPrice: 340,
  discountPct: 0,
  unit: 'per 250ml bottle',
  stock: 12,
  stockStatus: 'low_stock',
  rating: 4.3,
  reviewCount: 88,
  description: 'Systemic insecticide effective against sucking pests. Use on cotton, rice, and vegetables.',
  tags: ['insecticide', 'cotton', 'sucking pests'],
  minOrder: 1
},
{
  id: 'prod-004',
  name: 'Steel Khurpi (Weeding Tool) — Set of 3',
  vendor: 'Agro Tools India',
  vendorVerified: false,
  category: 'Tools',
  categorySlug: 'tools',
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_12949b3de-1777538344448.png",
  imageAlt: 'Three steel khurpi hand weeding tools with wooden handles laid on soil',
  price: 220,
  originalPrice: 280,
  discountPct: 21,
  unit: 'per set',
  stock: 0,
  stockStatus: 'out_of_stock',
  rating: 4.1,
  reviewCount: 54,
  description: 'Durable hardened steel blade with ergonomic wooden handle. Ideal for weeding and loosening soil.',
  tags: ['weeding', 'hand tool', 'soil'],
  minOrder: 1
},
{
  id: 'prod-005',
  name: 'Urea Fertilizer (46% Nitrogen)',
  vendor: 'Kisan Agro Supplies',
  vendorVerified: true,
  category: 'Fertilizers',
  categorySlug: 'fertilizers',
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_10efea551-1772359294682.png",
  imageAlt: 'White urea fertilizer granules poured from a green bag onto soil',
  price: 280,
  originalPrice: 290,
  discountPct: 3,
  unit: 'per 45kg bag',
  stock: 500,
  stockStatus: 'in_stock',
  rating: 4.8,
  reviewCount: 541,
  description: 'IFFCO Urea — top-dressing nitrogen fertilizer for all crops. Government regulated price.',
  tags: ['urea', 'nitrogen', 'all crops'],
  minOrder: 1
},
{
  id: 'prod-006',
  name: 'PM-40 Drip Irrigation Kit (1 Acre)',
  vendor: 'Jal Shakti Irrigation',
  vendorVerified: true,
  category: 'Irrigation',
  categorySlug: 'irrigation',
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_151f95048-1767695945277.png",
  imageAlt: 'Black drip irrigation pipes laid out in rows across a green vegetable field',
  price: 8400,
  originalPrice: 10500,
  discountPct: 20,
  unit: 'per kit (1 acre)',
  stock: 18,
  stockStatus: 'low_stock',
  rating: 4.6,
  reviewCount: 73,
  description: 'Complete drip irrigation kit with main line, sub-main, laterals, and drippers for 1 acre.',
  tags: ['drip', 'water saving', 'horticulture'],
  minOrder: 1
},
{
  id: 'prod-007',
  name: 'Organic Vermicompost (Earthworm Compost)',
  vendor: 'NatureFarm Organics',
  vendorVerified: true,
  category: 'Organic',
  categorySlug: 'organic',
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1174846d6-1772347292568.png",
  imageAlt: 'Dark brown organic vermicompost in an open jute sack on farm ground',
  price: 420,
  originalPrice: 500,
  discountPct: 16,
  unit: 'per 25kg bag',
  stock: 160,
  stockStatus: 'in_stock',
  rating: 4.9,
  reviewCount: 218,
  description: 'Premium quality vermicompost. Improves soil structure, water retention, and microbial activity.',
  tags: ['organic', 'compost', 'soil health'],
  minOrder: 2
},
{
  id: 'prod-008',
  name: 'Paddy Seeds — Swarna Sub-1 (Flood Tolerant)',
  vendor: 'Seed Masters Punjab',
  vendorVerified: true,
  category: 'Seeds',
  categorySlug: 'seeds',
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1d63ee08d-1772803366895.png",
  imageAlt: 'Golden paddy rice seeds in a burlap sack with rice stalks in background',
  price: 760,
  originalPrice: 850,
  discountPct: 11,
  unit: 'per 5kg bag',
  stock: 44,
  stockStatus: 'in_stock',
  rating: 4.6,
  reviewCount: 163,
  description: 'Flood-tolerant paddy variety. Survives 14 days submergence. Ideal for flood-prone areas.',
  tags: ['paddy', 'flood tolerant', 'kharif'],
  minOrder: 1
},
{
  id: 'prod-009',
  name: 'Battery-Operated Knapsack Sprayer 16L',
  vendor: 'Agro Tools India',
  vendorVerified: false,
  category: 'Tools',
  categorySlug: 'tools',
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1736ac5d8-1764657819365.png",
  imageAlt: 'Blue battery-operated knapsack sprayer being used in a vegetable field',
  price: 2850,
  originalPrice: 3400,
  discountPct: 16,
  unit: 'per unit',
  stock: 27,
  stockStatus: 'in_stock',
  rating: 4.2,
  reviewCount: 96,
  description: '12V battery-operated sprayer with 16L tank. 2.5 hours continuous spray on single charge.',
  tags: ['sprayer', 'battery', 'pesticide application'],
  minOrder: 1
},
{
  id: 'prod-010',
  name: 'Chlorpyrifos 20% EC — Termite Control',
  vendor: 'BharatAgri Chem',
  vendorVerified: true,
  category: 'Pesticides',
  categorySlug: 'pesticides',
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_10ef58591-1768298323748.png",
  imageAlt: 'Brown pesticide bottle with orange label for termite control chemical',
  price: 285,
  originalPrice: 320,
  discountPct: 11,
  unit: 'per 500ml',
  stock: 65,
  stockStatus: 'in_stock',
  rating: 4.0,
  reviewCount: 42,
  description: 'Broad-spectrum insecticide for soil and foliar application. Controls termites and soil insects.',
  tags: ['termite', 'soil insect', 'broad spectrum'],
  minOrder: 1
},
{
  id: 'prod-011',
  name: 'NPK 12-32-16 Complex Fertilizer',
  vendor: 'Coromandel Agri',
  vendorVerified: true,
  category: 'Fertilizers',
  categorySlug: 'fertilizers',
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1f60f1c52-1772359294724.png",
  imageAlt: 'Pink and grey NPK complex fertilizer granules in an open 50kg bag',
  price: 1480,
  originalPrice: 1650,
  discountPct: 10,
  unit: 'per 50kg bag',
  stock: 110,
  stockStatus: 'in_stock',
  rating: 4.5,
  reviewCount: 287,
  description: 'Balanced NPK complex for sugarcane, cotton, and oilseeds. Improves root development.',
  tags: ['sugarcane', 'cotton', 'complex'],
  minOrder: 1
},
{
  id: 'prod-012',
  name: 'Maize Hybrid Seeds — Pioneer 30V92',
  vendor: 'Green Fields Seeds',
  vendorVerified: true,
  category: 'Seeds',
  categorySlug: 'seeds',
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1315b6290-1768184171074.png",
  imageAlt: 'Yellow maize corn hybrid seeds in a transparent packet on soil background',
  price: 920,
  originalPrice: 1050,
  discountPct: 12,
  unit: 'per 4kg packet',
  stock: 38,
  stockStatus: 'in_stock',
  rating: 4.7,
  reviewCount: 201,
  description: 'High-yielding maize hybrid with excellent standability. 100-day maturity. Suitable for kharif.',
  tags: ['maize', 'corn', 'kharif', 'high yield'],
  minOrder: 1
}];


export const categories = [
{ slug: 'all', label: 'All Products', count: 12 },
{ slug: 'fertilizers', label: 'Fertilizers', count: 3 },
{ slug: 'seeds', label: 'Seeds', count: 3 },
{ slug: 'pesticides', label: 'Pesticides', count: 2 },
{ slug: 'tools', label: 'Tools & Equipment', count: 2 },
{ slug: 'irrigation', label: 'Irrigation', count: 1 },
{ slug: 'organic', label: 'Organic', count: 1 }];